### ISSUE TITLE
Brainstorm para indicações de ideias em projetos de software

### ISSUE THREAD

**Issue by radamesp7** [radamesp7/AbexII_G12_2024#1]
O brainstorming se aplica a disciplina de aprendizado baseado em experiências, onde os alunos em grupos indicam o que pode ser uma ideia de problema que possa ser solucionado com o desenvolvimento de um aplicativo de software e que tem uma finalidade prática. O brainstoriming deve gerar ideias entre os membros do grupo e precisa que se use como base o github para que possam trabalhar como grupo de trabalho e registrar as ideias conforme forem gerando as mesmas.

 Lista de Ideias:

**Comment by GustavoTelosm** [comment]
Problemas:

Demora para atendimento em Hospitais.
Falta de conhecimento em finanças.
Falta de conhecimento em investimentos.
falta de conhecimento em desenvolvimento pessoal.
Falta de controle sobre gastos.
impulso de consumo.
economias burras.
nenhuma fonte de renda além do trabalho tradicional.
baixo interesse em desenvolvimento.
automedicação sem controle.
saúde mental.
golpes digitais.
falta de conhecimento com tecnologias novas.
Escolha impulsiva e irracional de Candidatos políticos.
Analfabetismo.
Inglês baixo
segurança online
fake News.
ferramentas IA.
conteúdos de entretenimento
baixa autoestima
solidão
falta de apoio.
conhecimento politico.
conhecimento básico sobre economia brasileira.
baixo envolvimento em projetos da câmara dos deputados.
números de emergência.
primeiros socorros básicos.
controle de finanças particular.
baixa importancia com politica.
desenvolvimento pessoal baixo.
baixo interesse em obter conhecimento por cursos e outros...
baixo interesse em investimento pessoal.
